apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - service.yaml
  - networkpolicy.yaml
  - configmap.yaml
  - deployment.yaml

patches:
  - target:
      kind: ConfigMap
      name: agent-config
    patch: |-
      - op: add
        path: /data/EVAL_RUNNER_URL
        value: "http://eval-runner:8099"
