apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  annotations:
    kubernetes.io/reclaimPolicy: Delete
  labels:
    component: cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
